### ISSUE TITLE
Handle multiple versions of weather files

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/wx-files-frontend#71]
For a description of what "multiple versions" means, see https://github.com/pacificclimate/wx-files-service/issues/23

The meaning of "handle multiple versions" is really down to how the UI should present it to the user. We have a few options:
- "Pre-filter" main table on version. This might look like a drop-down above the main table that selects the version. Then all and only files matching that version are presented in the table. (Note: Don't show locations with no files for that version.)
- Add version as a column in the main table, and use filtering there, just like the other filters for other columns.
- Only present one or the other version, with two deployments of the same app differing only by configuration (selecting version). A title element would tell the user what version they are looking at.

It's hard to say which of these is more desirable. We should probably consult with others, a (very very simple) picture or wireframe conveying the options.

**Comment by corviday** [comment]
After discussion with @ssobie  and @rod-glover , we have decided on a dropdown labeled "Future-shifted Dataset" with options of "CMIP5+CWEC2016" and "CMIP6+CWEC2020". Subject to revision if that doesn't fit in gracefully, but I think it should, the table is pretty wide.

**Comment by rod-glover** [comment]
I restate my opinion:
- **Preferred**: Add that selector as separate selector above the entire (unchanged) table. The table is only going to be showing one version of the data at one time, so it is redundant to repeat it for every row in the table. And it adds another column to an already wide table.
- **Worse, not preferred**: Add the selector as a table column filter.

**Comment by corviday** [comment]
My initial plan was to have a dropdown that would let users swap between the CMIP5 and CMIP6 datasets. which would filter on a hidden "version" column using either that column's filter, or a filter set in table state. However, neither approach works; if the column is hidden, all data in it is utterly ignored by the table and cannot be filtered on by either method.

I agree that we don't really want a visible column with the CMIP5 and CMIP6 data, considering users are only going to want one at a time, and the table is already wide enough.

I think the next best course of action is to have the data filtered _before_ loading it into the table. I suggest two separate portal pages, one of which shows CMIP5 data and one of which shows CMIP6 data. They could link to each other, or they could both be linked from the landing page.
